apiVersion: 1

datasources:
  - name: postgres
    uid: tiyX_tTVz
    isDefault: true
    type: postgres
    url: postgres:5432
    database: dashboard
    user: grafana
    secureJsonData:
      password: $DASH_PGPASSWORD_GRAFANA
    jsonData:
      sslmode: disable # disable/require/verify-ca/verify-full
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: true
    editable: true
